### PR TITLE
Updates to dataset page

### PR DESCRIPTION
**Pull request by tanvirchahal**

### CODE REVIEW

**Comment by osahon-okungbowa** [comment]
@tanvirchahal please confirm if this PR still needs to be merged or can be closed.
it looks like you already implemented the features contained in this PR

**Comment by tanvirchahal** [comment]
@osahon-okungbowa it needs to be merged and deployed

**Comment by osahon-okungbowa** [comment]
ok @tanvirchahal . Reassigning to @MuhammadIsmailShahzad .

**Review by MuhammadIsmailShahzad — APPROVED** [review]
LGTM

**Pull request merged**
